name = "serverless-dns"
main = "./dist/worker.js"
workers_dev = true
# logpush job is setup to capture from envs ending: log, pro, or one
logpush = false
# use node_compat or custom build
# node_compat = true
compatibility_date = "2023-03-21"
send_metrics = false
minify = false
upload_source_maps = true

[build]
command = "npm run build"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[vars]
LOG_LEVEL = "error"
WORKER_ENV = "production"
CLOUD_PLATFORM = "cloudflare"

##################
#------PROD------#
##################
# wrangler doesn't yet support Workers Services and the new "Environments"
# github.com/cloudflare/cloudflare-docs/pull/3175/files
# github.com/cloudflare/wrangler2/issues/27
# developers.cloudflare.com/workers/platform/environments
[env.prod]
name = "basic-unbound"
minify = true
routes = [
  "sky.rethinkdns.com/*",
  "sky.bravedns.com/*",
  "basic.rethinkdns.com/*",
  "basic.bravedns.com/*",
  "free.bravedns.com/*",
]
# vars are not inherited
# workers/platform/environment-variables#environment-variables-via-wrangler
[env.prod.vars]
LOG_LEVEL = "error"
WORKER_ENV = "production"
CLOUD_PLATFORM = "cloudflare"

##################
#------ONE-------#
##################
[env.one]
name = "dns-one"
logpush = false
minify = true
routes = [
  "one.rethinkdns.com/*",
  "one.bravedns.com/*",
]

#analytics_engine_datasets = [
#   { binding = "METRICS", dataset = "ONE_M0" },
#    { binding = "BL_METRICS", dataset = "ONE_BL0" }
#]

[env.one.vars]
# just the error and request logs
LOG_LEVEL = "logpush"
WORKER_ENV = "production"
CLOUD_PLATFORM = "cloudflare"
CF_LOGPUSH_R2_PATH = "qlog/"

